export const bannedSettlerColonyVariations = [
	"israel",
	"state of israel",
	"the state of israel",
	"thestateofisrael",
	"zionist state",
	"zioniststate",
	"the zionist state",
	"the zionist jewish state",
	"zionist jewish state",
	"zionist regime",
	"zionist entity",
	"zionist occupied palestine",
	"zionist controlled land",
	"zio state",
	"the zio state",
	"the zio jewish state",
	"zionistan",
	"the jewish state",
	"the jewish state of israel",
	"jewish state",
	"jewish zionist state",
	"the jewish zionist state",
	"the jewish zionist state of israel",
	"zionist jewish state of israel",
	"promised land",
	"land of israel",
	"land of milk and honey",
	"chosen land",
	"ancestral land",
	"start-up nation",
	"the only democracy in the middle east",
	"where god promised us",
	"where the wailing wall is",
	"yisrael",
	"eretzyisrael",
	"eretz yisrael",
	"ereẓ yisrael",
	"am israel chai",
	"amIsraelchai",
	"yerushalayim",
	"medinat yisrael",
	"zion",
	"siyon",
	"tel aviv",
	"jerusalem israel",
	"jerusalem",
	"haifa",
	"eilat",
	"ashdod",
	"nazareth",
	"isr",
	"il",
	"idf",
	"iof",
	"zog",
	"jstate",
	"i.s.r.a.e.l",
	"i-s-r-a-e-l",
	"i_s_r_a_e_l",
	"🇮🇱",
	"isr43l",
	"1srael",
	"1srae1",
	"15r431",
	"lsrael",
	"izrael",
	"isreal",
	"issrael",
	"iszrael",
	"isr@el",
	"i$r@el",
	"i$rael",
	"i5rael",
	"!srael",
	"i$srae1",
	"i$rae1",
	"israe1",
	"i5ra3l",
	"!5r4e1",
	"israeI",
	"iѕгаеӏ",
	"🇮🇱srael",
	"i🇮🇱s🇮🇱r🇮🇱a🇮🇱e🇮🇱l",
	"thejewishstateofisrael",
	"jewishstateofisrael",
	"zioniststateofisrael",
	"zionistjewishstate",
	"zionistjewishstateofisrael",
	"zionistregimeofisrael",
	"zionistentityofisrael",
	"zionistoccupiedpalestine",
	"zionistcontrolledland",
	"zionistpromisedland",
	"landofisrael",
	"promisedlandofzion",
	"ancestrallandofjews",
	"landofmilkandhoney",
	"eretzisrael",
	"eretzyisrael",
	"medinatyisrael",
	"amIsraelChai",
	"startUpNation",
	"theOnlyDemocracyintheMiddleEast",
	"theholyland",
	"wheregodpromisedus",
	"wherethewailingwallis",
	"jerusalemisrael",
	"telavivisrael",
	"zionland",
	"zioncountry",
	"zionstate",
	"sacredzion",
	"eternaljerusalem",
	"savethezioniststate",
	"supportzioniststate",
	"standwithisrael",
	"defendisrael",
	"prayforisrael",
	"prayforzion",
	"peaceforisrael",
	"🇮🇱israel",
	"israel🇮🇱",
	"i🇮🇱sr🇮🇱ae🇮🇱l",
	"🇮🇱🇮🇱🇮🇱",
	"🕍israel",
	"isra✡️el",
	"israel.com",
	"israel.org",
	"gov.il",
	"idf.il",
	"knesset.gov.il",
	"jewland",
	"jstate",
	"zstate",
	"ziongov",
	"ziongovt",
	"ziongovofisrael",
	"ziongovernment",
	"zionified",
	"zionrules",
	"zionistheaven",
	"zionhomeland",
	"zzzionist",
	"jewwwwishstate",
	"israaael",
	"izzzyrael",
	"isxrael",
	"iszraeel",
	"i5raeeel",
	"izrrrael",
	"ezzrael",
	"isrrreel",
	"יִשְׂרָאֵל",
	"اسرائيل"
];
